Vue.component('page', require('./dynamic_components/Page.vue').default)
Vue.component('page-no-slider-pagination', require('./dynamic_components/PageNoSliderPagination.vue').default)
Vue.component('about', require('./dynamic_components/About.vue').default)
Vue.component('contact', require('./dynamic_components/Contact.vue').default)
Vue.component('testimonials', require('./dynamic_components/Testimonials.vue').default)
